// Demo adatok — akkor használjuk, ha nincs beállítva Supabase kulcs.
// Ugyanazt a formát követi, mint a supabase/migrations/0002_seed.sql.
import type { MenuCategory, MenuItem, Review, Unavailability, Restaurant } from "@/types";

const RESTAURANT_ID = "00000000-0000-0000-0000-000000000001";
const SEED_DATE = "2024-01-15T09:00:00.000Z";

export const mockRestaurant: Restaurant = {
  id: RESTAURANT_ID,
  name: "Zöld Sarok Vegan Bistro",
  description: "Prémium növényi alapú bistro a belváros szívében.",
  address: "1053 Budapest, Kossuth Lajos utca 12.",
  phone: "+36 1 234 5678",
  email: "asztal@zoldsarok.hu",
  hours: [
    { day: "Hétfő", hours: "Zárva" },
    { day: "Kedd – Csütörtök", hours: "12:00 – 22:00" },
    { day: "Péntek – Szombat", hours: "12:00 – 23:00" },
    { day: "Vasárnap", hours: "12:00 – 21:00" },
  ],
  max_daily_guests: 120,
  table_config: [
    { type: "standard", label: "Belső terem", count: 14, capacity: 4 },
    { type: "window", label: "Ablak melletti", count: 6, capacity: 2 },
    { type: "terrace", label: "Terasz", count: 8, capacity: 4 },
    { type: "bar", label: "Bár pult", count: 5, capacity: 1 },
    { type: "private", label: "Különterem", count: 1, capacity: 12 },
  ],
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const mockCategories: MenuCategory[] = [
  { id: "cat-1", restaurant_id: RESTAURANT_ID, name: "Levesek", slug: "levesek", description: null, sort_order: 1, created_at: SEED_DATE, updated_at: SEED_DATE },
  { id: "cat-2", restaurant_id: RESTAURANT_ID, name: "Előételek", slug: "eloetelek", description: null, sort_order: 2, created_at: SEED_DATE, updated_at: SEED_DATE },
  { id: "cat-3", restaurant_id: RESTAURANT_ID, name: "Főételek", slug: "foetelek", description: null, sort_order: 3, created_at: SEED_DATE, updated_at: SEED_DATE },
  { id: "cat-4", restaurant_id: RESTAURANT_ID, name: "Desszertek", slug: "desszertek", description: null, sort_order: 4, created_at: SEED_DATE, updated_at: SEED_DATE },
  { id: "cat-5", restaurant_id: RESTAURANT_ID, name: "Italok", slug: "italok", description: null, sort_order: 5, created_at: SEED_DATE, updated_at: SEED_DATE },
];

export const mockMenuItems: MenuItem[] = [
  {
    id: "item-1",
    category_id: "cat-1",
    name: "Sütőtökkrémleves",
    description: "Füstölt paprikás sütőtökkrém, pirított tökmag, kókusztejszín-örvény.",
    price: 2890,
    image_url: null,
    dietary_info: ["vegan", "gluten-free"],
    allergens: [],
    is_available: true,
    seasonal: true,
    is_new: false,
    portion_size: "300 ml",
    sort_order: 1,
    created_at: SEED_DATE,
    updated_at: SEED_DATE,
  },
  {
    id: "item-2",
    category_id: "cat-1",
    name: "Erdei gombaleves",
    description: "Vadgomba ragu leves, friss kakukkfűvel, tönkölybéles crostinival.",
    price: 3190,
    image_url: null,
    dietary_info: ["vegan"],
    allergens: ["gluten"],
    is_available: true,
    seasonal: false,
    is_new: false,
    portion_size: "300 ml",
    sort_order: 2,
    created_at: SEED_DATE,
    updated_at: SEED_DATE,
  },
  {
    id: "item-3",
    category_id: "cat-2",
    name: "Cékla-carpaccio",
    description: "Vékonyra szeletelt sült cékla, kesudió-ricotta, bazsalikomolaj, gránátalma.",
    price: 3490,
    image_url: null,
    dietary_info: ["vegan", "gluten-free"],
    allergens: ["nuts"],
    is_available: true,
    seasonal: false,
    is_new: true,
    portion_size: "1 adag",
    sort_order: 1,
    created_at: SEED_DATE,
    updated_at: SEED_DATE,
  },
  {
    id: "item-4",
    category_id: "cat-2",
    name: "Padlizsánkaviár",
    description: "Füstölt padlizsánkrém, szezámmagos lepénnyel és savanyú zöldségekkel.",
    price: 2990,
    image_url: null,
    dietary_info: ["vegan"],
    allergens: ["sesame", "gluten"],
    is_available: true,
    seasonal: false,
    is_new: false,
    portion_size: "1 adag",
    sort_order: 2,
    created_at: SEED_DATE,
    updated_at: SEED_DATE,
  },
  {
    id: "item-5",
    category_id: "cat-3",
    name: "Jackfruit gulyás",
    description: "Paprikás jackfruit ragu, hajdinával, erős paprikakrémmel.",
    price: 5490,
    image_url: null,
    dietary_info: ["vegan"],
    allergens: [],
    is_available: true,
    seasonal: false,
    is_new: true,
    portion_size: "400 g",
    sort_order: 1,
    created_at: SEED_DATE,
    updated_at: SEED_DATE,
  },
  {
    id: "item-6",
    category_id: "cat-3",
    name: "Grillezett karfiolsteak",
    description: "Egészben grillezett karfiol, kurkumás tahini szósz, pirított mandula, gránátalma.",
    price: 5290,
    image_url: null,
    dietary_info: ["vegan", "gluten-free"],
    allergens: ["nuts", "sesame"],
    is_available: true,
    seasonal: true,
    is_new: false,
    portion_size: "1 adag",
    sort_order: 2,
    created_at: SEED_DATE,
    updated_at: SEED_DATE,
  },
  {
    id: "item-7",
    category_id: "cat-3",
    name: "Bio zöldségrizottó",
    description: "Szezonális zöldségek, fehérboros rizottó, kesudió-parmezán.",
    price: 4990,
    image_url: null,
    dietary_info: ["vegan", "gluten-free"],
    allergens: ["nuts"],
    is_available: true,
    seasonal: true,
    is_new: false,
    portion_size: "350 g",
    sort_order: 3,
    created_at: SEED_DATE,
    updated_at: SEED_DATE,
  },
  {
    id: "item-8",
    category_id: "cat-3",
    name: "Seitan bourguignon",
    description: "Vörösboros seitan ragu, gyökérzöldségek, petrezselymes burgonyapüré.",
    price: 5690,
    image_url: null,
    dietary_info: ["vegan"],
    allergens: ["gluten"],
    is_available: true,
    seasonal: false,
    is_new: false,
    portion_size: "400 g",
    sort_order: 4,
    created_at: SEED_DATE,
    updated_at: SEED_DATE,
  },
  {
    id: "item-9",
    category_id: "cat-4",
    name: "Csokoládé fondant",
    description: "Folyós csokoládétorta, avokádó-krém, málnaszorbet.",
    price: 3290,
    image_url: null,
    dietary_info: ["vegan"],
    allergens: ["gluten"],
    is_available: true,
    seasonal: false,
    is_new: true,
    portion_size: "1 adag",
    sort_order: 1,
    created_at: SEED_DATE,
    updated_at: SEED_DATE,
  },
  {
    id: "item-10",
    category_id: "cat-4",
    name: "Kókusz-lime cheesecake",
    description: "Sütés nélküli kesudiós cheesecake, lime zselé, kókuszmorzsa.",
    price: 3190,
    image_url: null,
    dietary_info: ["vegan", "gluten-free"],
    allergens: ["nuts"],
    is_available: true,
    seasonal: true,
    is_new: false,
    portion_size: "1 szelet",
    sort_order: 2,
    created_at: SEED_DATE,
    updated_at: SEED_DATE,
  },
  {
    id: "item-11",
    category_id: "cat-5",
    name: "Házi kombucha",
    description: "Erjesztett, szénsavas tea, szezonális gyümölcsökkel ízesítve.",
    price: 1690,
    image_url: null,
    dietary_info: ["vegan", "gluten-free"],
    allergens: [],
    is_available: true,
    seasonal: true,
    is_new: false,
    portion_size: "300 ml",
    sort_order: 1,
    created_at: SEED_DATE,
    updated_at: SEED_DATE,
  },
  {
    id: "item-12",
    category_id: "cat-5",
    name: "Matcha latte",
    description: "Ceremóniás matcha, zab tej, agávé szirup.",
    price: 1590,
    image_url: null,
    dietary_info: ["vegan", "gluten-free"],
    allergens: [],
    is_available: true,
    seasonal: false,
    is_new: false,
    portion_size: "250 ml",
    sort_order: 2,
    created_at: SEED_DATE,
    updated_at: SEED_DATE,
  },
];

export const mockReviews: Review[] = [
  {
    id: "rev-1",
    restaurant_id: RESTAURANT_ID,
    booking_id: null,
    guest_name: "Nagy Eszter",
    rating: 5,
    comment: "A legszebb vegán étterem, ahol jártam — a karfiolsteak felejthetetlen élmény volt!",
    is_published: true,
    created_at: SEED_DATE,
  },
  {
    id: "rev-2",
    restaurant_id: RESTAURANT_ID,
    booking_id: null,
    guest_name: "Kovács Bence",
    rating: 5,
    comment: "Kifogástalan kiszolgálás, meghitt hangulat, és minden fogás színpompás volt.",
    is_published: true,
    created_at: SEED_DATE,
  },
  {
    id: "rev-3",
    restaurant_id: RESTAURANT_ID,
    booking_id: null,
    guest_name: "Tóth Zsófia",
    rating: 4,
    comment: "Nagyon finom volt a jackfruit gulyás, biztosan visszatérünk.",
    is_published: true,
    created_at: SEED_DATE,
  },
  {
    id: "rev-4",
    restaurant_id: RESTAURANT_ID,
    booking_id: null,
    guest_name: "Szabó Máté",
    rating: 5,
    comment: "Az étlap vizuálisan is lenyűgöző, és minden fogás igazi élmény volt.",
    is_published: true,
    created_at: SEED_DATE,
  },
];

export const mockUnavailability: Unavailability[] = [];
